### ISSUE TITLE
KeyError: "None of [Float64Index([nan], dtype='float64')] are in the [index]

### ISSUE THREAD

**Issue by CeeJay68** [data-to-insight/csc-validator-be-903#516]
**Describe the bug**
Loaded multiple files into the tool as the tool was processing I received a key error. Loaded files were Header, Episode, UASC, previous permanence, Reviews and Care Leavers. Also loaded last years Episode file. Ran tool with all rules selected during process received key error 'KeyError: "None of [Float64Index([nan], dtype='float64')] are in the [index]"'
Files run okay individually.

**To Reproduce**
As above

**Expected behavior**

**Screenshots**
![Key Error](https://user-images.githubusercontent.com/89516354/145575957-8dc930a4-3b63-4e9f-8759-ba20bd9b2695.png)

**Proposed fix (Optional)**

**Comment by dezog** [comment]
Hey Carl, many thanks for this. 

This is a puzzling one, looks like pandas running into trouble trying to find a null value in an index, but it's hard to say where.  

Due to the new logging system this shouldnt happen due to an individual rule - it must be to do with the data loading or report creation, but we'll need a little more info to track down exactly where it's going wrong.

It would be a massive help if you'd be able to try the following two things. 

Firstly, getting the logs produced when the error occurs by doing these steps:
  1. Repeat the process that generated the error exactly
  2. Bring up the JavaScript console by pressing Ctrl-Shift-K (Firefox) or Ctrl-Shift-I (Chrome) or Ctrl-Shift-J (Microsoft Edge)
        - there should be a message printed for each validation check, and some relating to file loading/report creation
  3. Once it finishes/crashes, select and copy all the text outputs by 
      - double-clicking inside the panel, 
      - then pressing Ctrl-A, followed by Ctrl+C
  4. Paste the logs in a comment here

Secondly, repeating the process with the individual files to try and figure out if it's a particular one that's causing it. We might be able to figure out what it is about the file that's causing the problem. 


Cheers - let me know how it goes, or if you won't have time to do so.

**Comment by CeeJay68** [comment]
Hi I’ve had issues replying to this with the requested information as it’s nearly 600 pages, so I’ve attached a pdf version which I can hopefully squeeze through our server restrictions. As an extra piece of information if I run the files independently they all run, process and complete with error reports. Let me know if you get this okay or whether I need to find an alternative option.
Many thanks

Carl Peirce
***@***.***<https://www.dorsetcouncil.gov.uk/>
Management Information Officer
Business Intelligence & Performance
Dorset Council
01305 224309 <tel:01305%20224309%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20>
dorsetcouncil.gov.uk<https://www.dorsetcouncil.gov.uk>

***@***.***<https://www.facebook.com/DorsetCouncilUK>
***@***.***<https://instagram.com/DorsetCouncilUK>
***@***.***<https://twitter.com/DorsetCouncilUK>

**Comment by dezog** [comment]
Thanks for this @CeeJay68 - this is the relevevant bit of the logs:
```
(anonymous) @ instrument.ts:130
instrument.ts:130 
        
       Caught Error! PythonError: Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 345, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 8, in <module>
  File "/lib/python3.9/site-packages/validator903/validator.py", line 59, in validate
    ds_results[table].loc[values, f'ERR_{error.code}'] = True
  File "/lib/python3.9/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/lib/python3.9/site-packages/pandas/core/indexing.py", line 648, in _get_setitem_indexer
    return self._convert_tuple(key)
  File "/lib/python3.9/site-packages/pandas/core/indexing.py", line 733, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/lib/python3.9/site-packages/pandas/core/indexing.py", line 1732, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, raise_missing=True)[1]
  File "/lib/python3.9/site-packages/pandas/core/indexing.py", line 1552, in _get_listlike_indexer
    self._validate_read_indexer(
  File "/lib/python3.9/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Float64Index([nan], dtype='float64')] are in the [index]"

```

The cause is nan's getting into the error list returned by one (or more) of the validation checks.

It's causing `Validator.validate()` to fail when it gets to validator.py @ line 59:
```
ds_results[table].loc[values, f'ERR_{error.code}'] = True
```

The quick fix is to just remove the nan's immediately before that happens, e.g. 
```
values = [i for i, not_nan in zip(values, pd.notna(values)) if not_nan]
```

In the longer term we should log where any rule returns invalid values so we can stop it happening at the source

**Comment by tab1tha** [comment]
Hi,
I have added that line of code and linked it in a pull request but I did not have a way of checking whether it works now (that is, this error is no longer raised).

**Comment by CeeJay68** [comment]
Thanks Tambe, I’ll recreate the test and see how it goes, will probably be Monday.

Carl Peirce
***@***.***<https://www.dorsetcouncil.gov.uk/>
Management Information Officer
Business Intelligence & Performance
Dorset Council
01305 224309 <tel:01305%20224309%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20>
dorsetcouncil.gov.uk<https://www.dorsetcouncil.gov.uk>

***@***.***<https://www.facebook.com/DorsetCouncilUK>
***@***.***<https://instagram.com/DorsetCouncilUK>
***@***.***<https://twitter.com/DorsetCouncilUK>
