### ISSUE TITLE
Bug: Rule 181 - wrongly flagging null values

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#517]
**Describe the bug**
@Steve-Far reports rule 181 is flagging null values for children looked after for 12 months

**To Reproduce**
Upload data including null values for any of:

CONVICTED
HEALTH_CHECK
IMMUNISATIONS
TEETH_CHECK
HEALTH_ASSESSMENT
SUBSTANCE MISUSE
INTERVENTION_RECEIVED or
INTERVENTION_OFFERED

**Expected behavior**
Null values should not trigger 181

**Comment by dezog** [comment]
similar to https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/520, from the code of the validation check, it looks like this shouldn't be happening. 

@Steve-Far would you be able to have a look into the actual text of the XML file, and see if the values being flagged for this are actually 'null' as in missing? It might be that empty strings ( `""` ) are getting shown as null's in the frontend.

**Comment by Steve-Far** [comment]
@dezog Yes, though I'm struggling to get into the tool, it says python loading but it's been doing it for 5 mins!

**Comment by Steve-Far** [comment]
@dezog I'm in... Looking at the XML it's where they are missing altogether, this one has no 'HEALTH_CHECK', 'INTERVENTION_RECEIVED' or 'INTERVENTION_OFFERED' and is flagging the error:

![image](https://user-images.githubusercontent.com/92323914/145979862-581745b6-5321-49c3-abbc-2fa23049253f.png)

The error is flagging 243 records which is most of the cohort

**Comment by dezog** [comment]
This is baffling - it looks like it should just not be happening due to the `oc2[fields_of_interest].notna()`:

![image](https://user-images.githubusercontent.com/63907524/146017828-d7cfb994-61b0-4ab6-aa57-b0f48f66c310.png)

**Comment by dezog** [comment]
My only other thought is that they're something to do with the XML ingress process

@SLornieCYC @bellt101 @crossls @PhilDeakin @JRycr @OgileOze - Would you mind having a look for this issue next time you run data through the tool, and mentioning whether you're using XML or CSV's?

**Comment by SLornieCYC** [comment]
Is this because it's evaluating the entire row, rather than checking each specific value?

```
            error_mask = (
                    oc2[fields_of_interest].notna()
                    & ~oc2[fields_of_interest].astype(str).isin(['0', '1'])
            ).any(axis=1)
```

If 
- any of the columns in row are not NA AND 
- any of the columns in row are not in (0, 1)

Then highlight all of the columns: 
```
fields_of_interest = ['CONVICTED', 'HEALTH_CHECK', 'IMMUNISATIONS', 'TEETH_CHECK', 'HEALTH_ASSESSMENT',
                                  'SUBSTANCE_MISUSE', 'INTERVENTION_RECEIVED', 'INTERVENTION_OFFERED']
```

This rule feels like it might need to be broken down further and handled in a similar way to how Phil did 503: https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/blob/ae1228009a887849187ce37fff74676626b34a87/validator903/validators.py#L5287

**Comment by tab1tha** [comment]
I read through the conversations and I have made a change that checks for the presence of the fields of interest first before doing the comparison. That should work. I will link it in a minute.

**Comment by dezog** [comment]
Can anyone reproduce this bug currently? We had a call with an LA yesterday who reported rule 181 being triggered 800+ times previously, but it seemed not to be showing up any more with the same input files. 

It's possible this has been fixed inadvertently

**Comment by dezog** [comment]
> Is this because it's evaluating the entire row, rather than checking each specific value?
> 
> ```
>             error_mask = (
>                     oc2[fields_of_interest].notna()
>                     & ~oc2[fields_of_interest].astype(str).isin(['0', '1'])
>             ).any(axis=1)
> ```

Sorry Stephen, thought I'd replied to this before xmas! I don't think this is the issue here; the two masks within the brackets are combined for each cell, then the resulting array is flattened to an entry per row by the `.any(axis=1)`

**Comment by SLornieCYC** [comment]
Well there's _something_ odd still going on with this rule but I can't quite figure it out.

1) All records in my OC2 file have valid data for these columns: `<IMMUNISATIONS>`, `<TEETH_CHECK>`, `<HEALTH_ASSESSMENT>`, `<SUBSTANCE_MISUSE>` (no NULLs, all 1s or 0s)
2) Some records in my OC2 file also have valid data for either `<HEALTH_CHECK>` or `<INTERVENTION_RECEIVED>` and/or `<INTERVENTION_OFFERED>` (but not both)
3) `<CONVICTIONS>` is entirely empty because we get that data from elsewhere and I won't bother with that until the live return.

The records with an additional column populated are triggering rule 181 despite having a legitimate value (i.e. 1 or 0). None of the records that only have data in columns common to all rows are in-error.


![image](https://user-images.githubusercontent.com/89449804/151518568-f2bb8c36-39e8-474c-8bd3-e479df851c48.png)
![image](https://user-images.githubusercontent.com/89449804/151518610-c85e1ed9-881c-4712-b622-414f4e877563.png)
![image](https://user-images.githubusercontent.com/89449804/151518684-b37207db-1c5f-4ffd-8f0b-6bca2f2ac353.png)

**Comment by dezog** [comment]
Excellent observation! I think you've cracked it there - when there's missing values in an integer column, `pd.read_csv` reads the whole column as floats (ie decimals) instead, so it can shove a NaN in there, which for some reason which... I guess must make sense at some level (🤷 ?), can exist as a numpy float, but not as an integer.

![image](https://user-images.githubusercontent.com/63907524/151538017-8d1e4553-95f3-4b7d-beed-5855421e1bb1.png)

So it looks like we'll either have to amend all the rules involving integer code comparisons to take account of this, or add a workaround to ingress, such converting the columns to object dtype which will allow mixing types within the column.

**Comment by dezog** [comment]
Incidentally it's possible the problem with error 202 saying the genders have changed year-to-year is down to this same issue, if one year contains missing values
