### ISSUE TITLE
Bug: Rule 187 - continuously looked after

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#534]
**Describe the bug**
Children who have not been continuously looked after (e.g. last episode `<DEC>` is before `collection_end`) are being treated as if they were.

**To Reproduce**
- Child has ceasing episode (`<REC>` != X1)  with `<DEC>` before `collection_end`
- Child has either an AD1 or OC3 record with at least one relevant column filled

**Expected behavior**
Children who have not been continuously looked after during the year should be disregarded by this rule.

**Screenshots**

![image](https://user-images.githubusercontent.com/89449804/147252447-c4328118-23e1-4148-b687-dcc5adc14398.png)

![image](https://user-images.githubusercontent.com/89449804/147253028-2b1acee7-b6dd-47d5-b3bd-5ec3509bb5d8.png)

**Proposed fix**
Don't know! Can't see anything wrong with the python and the test data seems okay, but in the tool front-end I'm getting this for multiple records.

**Comment by tab1tha** [comment]
Thank you @SLornieCYC . This should be because the description of CONTINOUSLY_LOOKED_AFTER and code that checks for it, does not include a check for whether or not DEC is before/after the collection_end date. Adding that should solve it.

> If count of episodes in current year = ‘0’
or any episode has <LS> = ‘V3’ or ‘V4’
and <DEC> >=
<COLLECTION_START_DATE> or Null
or any episode<DEC> >=
<COLLECTION_START_DATE> and
<REC> not = ‘X1’
or any episode <RNE> = ‘S’ and
<DECOM> >
<COLLECTION_START_DATE> Then
<LOOKED_AFTER_CONTINUOUSLY>
= ‘N’ else
<LOOKED_AFTER_CONTINUOUSLY>
=’Y’

**Comment by dezog** [comment]
@tab1tha as discussed, following the CONTINUOUSLY_LOOKED_AFTER definition in the validation checks doc could give wrong results if someone uploads a file including episodes beyond the current collection year, but that doesn't seem to be what's causing this bug.

It does seem to be a problem with that function though -- I just got this by email:

> I noticed some of the same young people have error 191: “Child has been looked after continuously for at least 12 months at 31 March but one or more data items relating to children looked after for 12 months have been left blank”, which might fit with your suggestion that the ‘CONTINUOUSLY_IN_CARE’ flag is at the root of these issues.

**Comment by tab1tha** [comment]
This bug no longer appears and must have been inherently fixed by one of the tool updates.
