### ISSUE TITLE
Bug: Rule 164/169/179/1015- Missing postcode info should not cause errors for 'Z1' episodes

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#551]
**Describe the bug**
LA reports getting bugs for episodes marked placement type Z1: 'Other placements (must be listed on a schedule sent to DfE with annual submission)'

These apparently don't have to have postcode info, for example a child living on barge.

This does makes sense but as it's not mentioned in checks document - @PhilDeakin @bellt101 @Steve-Far @SLornieCYC can anyone confirm this just to be sure?

This affects all rules based on postcode-derived fields: 164/169/179/1015 - maybe there are others

**To Reproduce**
Load episode where placement type is Z1, and PL_POST is omitted

**Expected behavior**
if Z1, dont return error for those rows

**Comment by tab1tha** [comment]
Can I make a pull request for this or should we wait for confirmation first?. @dezog

**Comment by dezog** [comment]
Go for it. This would also include 392B I think

**Comment by dezog** [comment]
Additionally UASC do not need a HOME_POST or PL_DISTANCE, so watch out for that

**Comment by SLornieCYC** [comment]
Speaking only from my own experience, we have provided placement postcodes for Z1 placements in the past and I can't see anything in the guidance documents that indicates otherwise?  Placement **provider** is explicitly noted as not required for Z1 but that's the only reference I can find.

I would have thought that a Z1 placement without a valid postcode would be treated in the same way as any other placement, either by manually overriding with an appropriate proxy value or submitting an error-bypass request to DFE. For example:

![image](https://user-images.githubusercontent.com/89449804/151526711-0bca338a-7dab-434b-9f77-bb521669fc90.png)
![image](https://user-images.githubusercontent.com/89449804/151527051-a24ce2da-c423-4125-9277-74dac89eca12.png)

Given the guidance is quite explicit about providing postcodes even for adoption records I don't see why Z1 placements would be exempt:

![image](https://user-images.githubusercontent.com/89449804/151529921-b0ab0378-be73-4bae-831c-c947af38c469.png)
![image](https://user-images.githubusercontent.com/89449804/151530090-76696650-1d32-40a2-87dd-8cc3030f5758.png)

EDIT: We're supposedly due to get the test site for SSDA903 in mid-February so maybe this is one to test out how the rules work in practice in the DFE portal?

**Comment by tab1tha** [comment]
@SLornieCYC I agree. If we have not figured it out by then, it will be good to see how it works in the DfE portal.

**Comment by dezog** [comment]
Yeah, it does make sense these cases would have to be bypassed explicitly, good point. 

Agree that it'll be worth checking out what the DfE portal actually does though; it's possible it doesnt do exactly as you'd expect from the guidance

For example https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/552, where the guidance seems quite explicit that previous values must be updated, but the portal did seem happy with 'UN5' one year, then a filed-in UPN the next (comparing consecutive years' csv's downloaded from the DfE site last year)

**Comment by SLornieCYC** [comment]
(Belated) Tested in DFE portal this year and rules 164 and 169 definitely trigger when there is no PL_POST entered for a Z1 episode.

**Comment by tab1tha** [comment]
> (Belated) Tested in DFE portal this year and rules 164 and 169 definitely trigger when there is no PL_POST entered for a Z1 episode.

Hi @SLornieCYC, thank you for looking into this.
Tagging in @WillLP-code who is now in charge of the project.
