### ISSUE TITLE
Bug: Rule 577 & 578 - Don't work with multiple care periods

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#563]
**Describe the bug**
If a child has more than one care period during the year (i.e. ended a series of consecutive episodes with REC <> 'X1' and later started another series of episodes with RNE = 'S') these rules currently flag Missing events that are dated within the later care period as in-error because the dates are after the final DEC of the previous care period (ending REC <> 'X1').

**To Reproduce**
Steps to reproduce the problem, e.g.:
- Upload 'Episodes' and 'Missing CSV's, where:
   - 'Episodes' contains a child with one or more episodes covering two distinct care periods.
   - 'Missing' contains a child with one or more missing events that take place after the first care period finished but within the date range of the later care period (which may still be open at collection end!).
- Errors are displayed for the legitimate missing events.

**Expected behavior**
Missing events that exist within a care period (one or more consecutive episodes) should not trigger these errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/89449804/153192586-a71f2079-5e64-4e56-bfd1-570e81736ba7.png)

![image](https://user-images.githubusercontent.com/89449804/153191909-7741cdb5-85b5-40c4-988f-617fff1a572e.png)

Note that here both Missing events are dated within the second care period but are in-error against the first care period (in this case both care periods present as single episodes, but they could equally exist as multiple episodes across one or more years).

**Comment by tab1tha** [comment]
At first glance, This could be because `>` was used instead of `!=` in the definition of error_577. Line 573 of the screenshot.
![image](https://user-images.githubusercontent.com/42181805/153466136-8bf3aa7f-3d85-4024-a057-8319d29a3a53.png)

**Comment by dezog** [comment]
good thought, but i think this one'll take a bit more tinkering, as we have to figure out if it's actually outside a period of care, but currently it just triggers if any period care has already ended

**Comment by tab1tha** [comment]
Sidenote.
I think I remember why we changed the sign: The definition of 577 `MIS_END!=DEC` would have coincided with the definition of 578 `MIS_END>DEC`

**Comment by tab1tha** [comment]
I have considered adjusting these rules such that they compare MIS_START and MIS_END with the DEC of the most recent period of care. The proposes fix is outlined below:

This will involve detecting distinct periods of care per child. A period of care could be made up of one episode or two or more **consecutive** episodes whose legal status are neither V3 nor V4 (non-respite periods of care are used by default, see screenshot attached). 
![image](https://user-images.githubusercontent.com/42181805/155577536-4feebcad-f41b-4f35-ab30-09cf19784876.png)

let 
`poc_DECOM` = period of care DECOM
`poc_DEC` = period of care DEC

When episodes are sorted by DECOM, the DECOM of the first episode will be assigned to `poc_DECOM` and `poc_DEC` will be updated to that of the next consecutive episode.

Consecutiveness between episodes will be checked by `LS not V3 or V4` and `DEC == DECOM ` between the previous episode and the next. If any of the conditions is not satisfied, that period of care is stopped and a new poc is started by assigning the next episode's DECOM and DEC to poc_DECOM and poc_DEC respectively.

**Desired result:**
All episodes in a period of care will have a pocDECOM that corresponds to the DECOM of the first episode and a poc_DEC that corresponds to the DEC of the last episode in that period of care.

In the end, rules such as these (577, 578) will be comparing to poc_DEC instead of the simple DEC of the child in question. @dezog

**Comment by dezog** [comment]
@SLornieCYC do you know if a missing episode can overlap between two individual placement episodes? the guidance doesnt seem to forbid it but some of the rule descriptions could be read as implying it:

![image](https://user-images.githubusercontent.com/63907524/155719040-24888f53-0bf3-466c-94ef-a66415d8000a.png)

**Comment by dezog** [comment]
@tab1tha that all sounds sensible. bear in mind the goal is to have it trigger only for missing episodes which are not entirely within a period of care, so once you have a row for each period of care:
- do a left merge with the missing table. 
  - each of a childs poc's will have a row for each missing episode
  - pretty sure if they have a missing period but no episodes, that should be an error - any idea @SLornieCYC ?
- make a mask for each row of this table: `True` if the missing ep is completely within the poc
  - make sure to handle the cases where the final DEC and/or MIS_END are null correctly
- if a MIS_END/START if within any POC then it's valid. something like:
  - `merged.groupby('original_missing_index')['within_poc_mask'].max()`

the code in rule 364 may be of use to you, it also works with working out periods of consecutive episodes

**Comment by tab1tha** [comment]
There is a pertinent question that we have not answered: What defines the the relationship between the MIS_STARTs and DECs of a child that has multiple missing episodes and multiple episodes.

consider rule 578 where MIS_START should not be greater than DEC, 
if, for the same child, we have 
MIS_STARTS: `MS1`, `MS2`, `MS3`
DECs: `DEC1`, `DEC2`, `DEC3`

Do we simply compare in chronological order?( i.e compare `MS1-DEC1`, `MS2-DEC2`...) or do we take `MS1` and compare it with `DEC1`, `DEC2`, and `DEC3` before determining if `MS1` will flag the error?.
What of the scenario where 
`MS1 >DEC1` (fail)
but `MS1 < DEC2` (pass), should `MS1` flag the error?.

Sidenote, if we want to consider chronological comparison we should think of what happens when there are an unequal number. For example, 2 MIS_STARTS and 3 DECs.

@dezog @PhilDeakin  @SLornieCYC

**Comment by dezog** [comment]
So, I think the point of these rules is basically that any MIS_START or MIS_END must be during a period of care. 

![image](https://user-images.githubusercontent.com/63907524/155979683-1a26209d-4633-4dde-a5e9-51574ce074b3.png)

So as long as there is one period of care's 'POCC' and 'POCCOM' (pale blue lines) that they fall between, they are OK.

That's the reason for `merged.groupby('original_missing_index')['within_poc_mask'].max()`:
- after the merge (POCs table <-> Missing table), for each missing episode, there is a row for each of that child's periods of care
- for each row, theres a column `'within_poc_mask'` - True if POCCOM < MIS_START/END < POCC, else False
- then if ANY of these is true for a missing episode, it passes, so groupby the Missing table index, and take the max

The MIS_START & MIS_END marked in green is what I was trying to get at in my question above, but looking again it sounds like that's fine unless they've remained missing ever since a new care episode started, in which case it triggers 575

**Comment by tab1tha** [comment]
Thank you.
