### ISSUE TITLE
Bug: Rule [186] - [Children aged 4 or over at the start of the year and children aged under 17 at the end of the year and who have been looked after for at least 12 months continuously should have a Strengths and Difficulties (SDQ) score completed.   ]

### ISSUE THREAD

**Issue by bellt101** [data-to-insight/csc-validator-be-903#620]
**Describe the bug**
Whilst checking our data I think this rule is checking whether there is a SDQ Score and SDQ Reason within the OC2 file, where as you dont need a reason if you have a score and dont need a score if you have a reason.  Its currently showing 585 errors within our file, it is correctly discounting the under 4 and over 

**To Reproduce**
Upload a file where OC2 file has A SDQ Score and SDQ Reason this should flag an error, SDQ Score has a value and SDQ Reason is null should not flag an error and vice versa.

**Expected behavior**
No error should be flagged if either of the SDQ Score or SDQ Reason is entered.

**Screenshots**

**Proposed fix (Optional)**
If you have an idea of what might need changing in the code outline that here
The code looks like it is checking the correct values, and that there is no blank in either field, so not sure why this is not working correctly.
& oc2[['SDQ_SCORE', 'SDQ_REASON']].isna().any(axis=1)

I have downloaded the CSV on its own and I now only get errors for Error 188 and 189 (17 errors) and these are based on the fact that there is an SDQ submitted for a 4 year old and under or 17 and over, these are valid errors within the file,

**Comment by SLornieCYC** [comment]
Oops!  Think this is my fault from trying to fix this rule before (it didn't used to consider `<SDQ_REASON>` at all). Ref https://github.com/data-to-insight/quality-lac-data-beta-validator/issues/598 and https://github.com/data-to-insight/quality-lac-data-beta-validator/pull/605.

It looks like `& oc2[['SDQ_SCORE', 'SDQ_REASON']].isna().any(axis=1)` actually needs to be "not" (i.e. prefixed with **~**) to only return those that **don't** have a value in either column.  Or be changed to `.all` instead of `.any`, maybe? The test data will need updating as well as apparently that's all wrong too..

**Comment by SLornieCYC** [comment]
Hah. DFE have just issued revised validation guidance that now includes `<SDQ_REASON>` for this rule which means #598 and #605 are correct - apart from me having got the filter the wrong way around per this bug!

https://www.gov.uk/government/publications/children-looked-after-return-2022-to-2023-technical-specifications
