### ISSUE TITLE
Bug: Rule 205B - DUC is same in both years but error is flagged.

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/csc-validator-be-903#626]
**Describe the bug**
Sample data that was wrongly flagged by the rule is included.

**To Reproduce**
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/TAMBE~1.TAB/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/TAMBE~1.TAB/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/TAMBE~1.TAB/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>

Child | Affected   Table | Error   Row | Error   Code | Affected   Table | Error   Description
-- | -- | -- | -- | -- | --
aaa30 | UASC | 0 | 205B | UASC | Child   previously identified as UASC is also UASC this year, but date UASC ceased in   both years does not support this.
aaa32 | UASC | 1 | 205B | UASC | Child   previously identified as UASC is also UASC this year, but date UASC ceased in   both years does not support this.
bbb19 | UASC | 2 | 205B | UASC | Child   previously identified as UASC is also UASC this year, but date UASC ceased in   both years does not support this.
ccc05 | UASC | 3 | 205B | UASC | Child   previously identified as UASC is also UASC this year, but date UASC ceased in   both years does not support this.
ddd29 | UASC | 4 | 205B | UASC | Child   previously identified as UASC is also UASC this year, but date UASC ceased in   both years does not support this.
eee56 | UASC | 5 | 205B | UASC | Child   previously identified as UASC is also UASC this year, but date UASC ceased in   both years does not support this.

</body>

</html>

**Expected behavior**
All the above rows should not have been flagged. The DUC is the same in both years.

**Screenshots**

**Proposed fix (Optional)**
Check if the rule logic should be negated. It might be acting directly opposite to how it should.

**Comment by SLornieCYC** [comment]
Looking at the python I think the problem may lie here:

1. Mis-matched data frames (uasc vs uasc_last)
https://github.com/data-to-insight/quality-lac-data-beta-validator/blob/9cefcfd489f4afda2307901dcdd9239cd7a4185e/validator903/validators.py#L4098


2. DOB18 is then included in merged_current
https://github.com/data-to-insight/quality-lac-data-beta-validator/blob/9cefcfd489f4afda2307901dcdd9239cd7a4185e/validator903/validators.py#L4106


3. When it should actually be included in merged_last instead
https://github.com/data-to-insight/quality-lac-data-beta-validator/blob/9cefcfd489f4afda2307901dcdd9239cd7a4185e/validator903/validators.py#L4110


4. Because it is then compared to DUC_last which comes from merged_last
https://github.com/data-to-insight/quality-lac-data-beta-validator/blob/9cefcfd489f4afda2307901dcdd9239cd7a4185e/validator903/validators.py#L4121


5. The above issue (points 1-4) is repeated in rule 205C immediately below but DOB18 doesn't appear to actually be used in that rule and is probably leftover from copying the first rule as the starting point for the second!
https://github.com/data-to-insight/quality-lac-data-beta-validator/blob/9cefcfd489f4afda2307901dcdd9239cd7a4185e/validator903/validators.py#L4203

**Comment by WillLP-code** [comment]
Hi @SLornieCYC a few small things. I'm grappling with the 903 and I can't find a way to run the tests via the command line, am I just missing it?

I'm just looking at these three bugs and by the looks of the data frames used to test rule 205B, it is failing rows where the DUC is the same both years, but where it's the 18th birthday, so this seems to be intentional. I'm still looking but I'm wondering if this intentional fail has caused other unintentional fails.

Finally, looking at what you've said above, it _shouldn't_ matter if DOB18 comes from UASC or UASC last as they should produce the same date (presumably when someone is 18 and is no longer UASC) so I'm not sure the error comes from there, but I'm happy to be corrected.

**Comment by SLornieCYC** [comment]
Hi @willLPD2I, hopefully this will help:

>  I'm grappling with the 903 and I can't find a way to run the tests via the command line, am I just missing it?

When we were building the tool we were using `poetry run pytest tests/test_validators.py::TEST_FUNCTION_NAME` - where TEST_FUNCTION_NAME is a rule test function, e.g. test_validate_357.


> I'm just looking at these three bugs and by the looks of the data frames used to test rule 205B, it is failing rows where the DUC is the same both years, but where it's the 18th birthday, so this seems to be intentional.

This is the DFE rule definition (Error code, Description, Coding rule and comments, Coding description):

![image](https://user-images.githubusercontent.com/89449804/210731948-e1966c99-9239-4580-8d61-b8bdd509e428.png)


> Finally, looking at what you've said above, it shouldn't matter if DOB18 comes from UASC or UASC last as they should produce the same date (presumably when someone is 18 and is no longer UASC) so I'm not sure the error comes from there, but I'm happy to be corrected.

UASC and UASC last come from different source files so may have different child records in them - unless the child rows exactly match in index position between the two won't using the DOB from the other data frame for DOB18 return the wrong data?

**Comment by WillLP-code** [comment]
Hi @SLornieCYC this is really helpful, thank you. I realised whilst doing this that in the bug report we have a reproduction of the error report produced that shows the bug, but not the data that produces it, so I've moved to looking at the other bugs at the moment.

Looking back at DOB 18, you're right. It's assigning DOB18 to rows without checking that it's assigning the DOB18 to the child with the same ID. I think that slipped past me because it seems like an obvious thing to not do I didn't realise someone would do it.

I'm going to continue looking at the other bugs today. I'll probably post in the issues for them as a way of keeping notes on what I've found. As always, your insight on those notes is really appreciated.
